### ISSUE TITLE
Update naming for all implementations so that they are not redundant

### ISSUE THREAD

**Issue by aldarisbm** [aldarisbm/memory#10]
eg pinecone store should not be `NewPinecone` , it should just be `New` same for all of the other implementations

**Comment by Swarnlataaa** [comment]
I would like to take this up, please guide me further

**Comment by aldarisbm** [comment]
ideally just go through all of the implementations such as :

https://github.com/aldarisbm/memory/blob/5023c32d565924060889891e6d4608deddcce085/embeddings/openai/openai.go#LL15C6-L15C23

And make sure that they are consistent, the name of the package is openai already, and its under embeddings. I don't think it should be called `NewOpenAIEmbedder`, but probably just `New` so that people can call it as `openai.New` 

I'm open to suggestions.
